# Inteligencia Artificial

## Capítulo 2

### Matemática Básica para Ciencias de Datos

- **Unidad 1.** Introducción
- **Unidad 2.** Matemática Básica para Ciencias de Datos
- **Unidad 3.** Entendiendo las Ciencias de Datos: Vector
- **Unidad 4.** Entendiendo las Ciencias de Datos: Matriz
- **Unidad 5.** Entendiendo las Ciencias de Datos: Derivativas

**Nombre:** Alan Israel Palma Travez

# Quiz

___

## Q 02-01

### Cree ejemplos de vector cero, vector unitario, matriz cuadrada, matriz diagonal, matriz identidad y matriz simétrica uno por uno, y represente vectores y matrices con NumPy.

In [2]:
import numpy as np

# Vector cero
vector_cero = np.zeros(5)
print("Vector Cero:\n", vector_cero)

# Vector unitario
vector_unitario = np.ones(5)
print("Vector Unitario:\n", vector_unitario)

# Matriz cuadrada
matriz_cuadrada = np.random.rand(3, 3)
print("Matriz Cuadrada:\n", matriz_cuadrada)

# Matriz diagonal
matriz_diagonal = np.diag([1, 2, 3])
print("Matriz Diagonal:\n", matriz_diagonal)

# Matriz identidad
matriz_identidad = np.eye(3)
print("Matriz Identidad:\n", matriz_identidad)

# Matriz simétrica
matriz_simetrica = np.array([[1, 2, 3], [2, 4, 5], [3, 5, 6]])
print("Matriz Simétrica:\n", matriz_simetrica)

Vector Cero:
 [0. 0. 0. 0. 0.]
Vector Unitario:
 [1. 1. 1. 1. 1.]
Matriz Cuadrada:
 [[0.3077127  0.59088495 0.3643891 ]
 [0.73024803 0.06955856 0.59564067]
 [0.24680547 0.86491516 0.65572123]]
Matriz Diagonal:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]
Matriz Identidad:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Matriz Simétrica:
 [[1 2 3]
 [2 4 5]
 [3 5 6]]


___

## Q 02-02

### Las acciones de tres empresas A, B y C son 1 millón de wones, 800.000 wones y 500.000 wones, respectivamente. Queremos encontrar la cantidad necesaria para comprar 3, 4 y 5 acciones de estas acciones, respectivamente.

1) Exprese el precio y la cantidad de las acciones como vector p y vector n, respectivamente y codificados con NumPy.

In [3]:
# Precio de acciones
p = np.array([1e6, 8e5, 5e5])
print("Precio de acciones:\n", p)

# Cantidad de acciones
q = np.array([3, 4, 5])
print("Cantidad de acciones:\n", q)

Precio de acciones:
 [1000000.  800000.  500000.]
Cantidad de acciones:
 [3 4 5]


2) La cantidad necesaria para comprar acciones se expresa mediante multiplicación y el valor se calcula mediante la operación Numpy.

In [6]:
# Cantidades necesarias para comprar acciones
cantidad_necesaria = p * q
print("Cantidad necesaria para comprar acciones:")
print(f"Empresa A: ${cantidad_necesaria[0]}")
print(f"Empresa B: ${cantidad_necesaria[1]}")
print(f"Empresa C: ${cantidad_necesaria[2]}")

Cantidad necesaria para comprar acciones:
Empresa A: $3000000.0
Empresa B: $3200000.0
Empresa C: $2500000.0


___

## Q 02-03

### Cuando se ejecuta el siguiente código, todos los datos de la imagen numérica MNIST se convierten en vectores para crear una única matriz NumPy X. Utilice esta matriz para resolver el siguiente problema.
```
from sklearn.datasets import load_digits
X=load_digits().data
```

1) Encuentre la similitud entre la primera imagen y la décima imagen usando el producto escalar.

In [4]:
from sklearn.datasets import load_digits
import numpy as np

X=load_digits().data

print(X.shape)

# Encontrar la similitud entre la primera y decima imagen
similarity = np.dot(X[0], X[9])
print(f"Similitud entre la primera y décima imagen: {similarity}")

(1797, 64)
Similitud entre la primera y décima imagen: 2807.0


2) Encuentre la similitud para una combinación de todas las imágenes usando el producto escalar, ¿cómo sería eficiente implementarlo (pista: usando matrices y multiplicación de matrices)?


In [10]:
# Encontrar la  similitud para una conbinación de todas las imágenes
similarity_all = X @ X.T

# Si queremos acceder a la similitud entre la imagen 0 y la imagen 9
print(f"Similitud entre la imagen 0 y la imagen 9: {similarity_all[0, 9]}")
# Si queremos acceder a la similitud entre la imagen 5 y la imagen 7
print(f"Similitud entre la imagen 5 y la imagen 7: {similarity_all[5, 7]}")

Similitud entre la imagen 0 y la imagen 9: 2807.0
Similitud entre la imagen 5 y la imagen 7: 1967.0


___

## Q 02-04

### Calculate the following inverse matrix.


![matrix.png](attachment:matrix.png)

___

## Q 02-05

### El problema del precio de la vivienda en Boston es un problema de predicción del precio de la vivienda en cada ciudad de Boston (EE.UU.) utilizando características como el índice de delincuencia y la contaminación atmosférica de la zona. Puede importarse del paquete scikit-learn. Encuentre el vector de pesos x cuando el problema del precio de la vivienda en Boston se resuelva con el modelo de predicción lineal Ax=b. Los datos matriciales y vectoriales pueden obtenerse como sigue. Aquí, para simplificar el problema, limitamos los datos de entrada a la tasa de criminalidad (CRIM), la calidad del aire (NOX), el número de habitaciones (RM) y la edad (AGE), y sólo se utilizaron cuatro datos.

Ejecute el código siguiente para comprobar si la magnitud o el signo del vector de pesos obtenido al ejecutar el programa se ajusta a la noción común. Para ello, interprete la salida impresa para todos los factores: CRIM, NOX, RM y EDAD.

(※ Escriba la salida interpretada como "el precio de la vivienda está en proporción inversa a la tasa de criminalidad (CRIM)").
```
import pandas as pd
import numpy as np

data_url = "http://lib.stat.cmu.edu/datasets/boston"
boston = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
X = np.hstack([boston.values[::2, :], boston.values[1::2, :2]])
y = boston.values[1::2, 2]
A=X[:4, [0,4,5,6]] # ‘CRIM’,’NOX’,’RM’,’AGE’
b=y[:4]
```

In [26]:
import pandas as pd
import numpy as np

data_url = "http://lib.stat.cmu.edu/datasets/boston"
boston = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
X = np.hstack([boston.values[::2, :], boston.values[1::2, :2]])
y = boston.values[1::2, 2]
A=X[:4, [0,4,5,6]] # ‘CRIM’,’NOX’,’RM’,’AGE’
b=y[:4]

print("Dimensión de la Matriz A:\n", A.shape)
print("Dimensión del Vector b:\n", b.shape)
print("Matriz A:\n", A)
print("Vector b:\n", b)

Dimensión de la Matriz A:
 (4, 4)
Dimensión del Vector b:
 (4,)
Matriz A:
 [[6.320e-03 5.380e-01 6.575e+00 6.520e+01]
 [2.731e-02 4.690e-01 6.421e+00 7.890e+01]
 [2.729e-02 4.690e-01 7.185e+00 6.110e+01]
 [3.237e-02 4.580e-01 6.998e+00 4.580e+01]]
Vector b:
 [24.  21.6 34.7 33.4]


In [27]:
# Invertir la matriz A
A_inv = np.linalg.inv(A)

# Calcular la solución del sistema de ecuaciones Ax = b
x = A_inv @ b
print("Solución x:\n", list(map(float, x)))

# Encontar el modulo del vector x
modulo_x = np.linalg.norm(x)
print("Módulo del vector x:\n", float(modulo_x))

features = ['CRIM', 'NOX', 'RM', 'AGE']

for i, feat in enumerate(features):
    if x[i] > 0:
        print(f"El precio de la vivienda está en proporción directa con {feat}.")
    else:
        print(f"El precio de la vivienda está en proporción inversa con {feat}.")

Solución x:
 [-312.710043270391, -115.19394234554909, 14.499646531804672, -0.11325931735032801]
Módulo del vector x:
 333.56778635308854
El precio de la vivienda está en proporción inversa con CRIM.
El precio de la vivienda está en proporción inversa con NOX.
El precio de la vivienda está en proporción directa con RM.
El precio de la vivienda está en proporción inversa con AGE.


___

## Fin